### PR TITLE
corrected minor syntax-error

### PR DESCRIPTION
**Pull request by DJCrashdummy**

### CODE REVIEW

**Comment by clefebvre** [comment]
Thanks, fixed upstream https://translations.launchpad.net/linuxmint/latest/+pots/linuxmint-installation-guide/de/208/+translate.

**Comment by DJCrashdummy** [comment]
is there something additional which has to be done, since the first link in the list is still broken?
https://linuxmint-installation-guide.readthedocs.io/de/latest/partitioning.html#disks-and-partitions-under-linux

**Comment by to-ba** [comment]
Take a tea and wait some days. ;-)
https://linuxmint-installation-guide.readthedocs.io/ have to be synced with https://translations.launchpad.net

**Comment by DJCrashdummy** [comment]
sorry to ask again, but after more than 2 months everything should be synced, but as already asked:
the first bullet/link in the list at https://linuxmint-installation-guide.readthedocs.io/de/latest/partitioning.html#disks-and-partitions-under-linux is still broken?!

**Pull request closed without merging**
